### ISSUE TITLE
Create a new file for yinghui's hometowm 

### ISSUE THREAD

**Issue by miaoy2** [githubteacher/friendly-octo-pancake#4]
## San Diego, CA
- [ ] Create a branch1
- [ ] Add comments (make changes)
- [ ] Open a Pull Request
- [ ] Collaboration
- [ ] Seek approval
- [ ] Merge PR

**Comment by hectorsector** [comment]
@miaoy2 awesome work -- you can click the `Edit` button next to the title if you'd like to include your username instead of `githubteacher`
